/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iutforces_user;

import java.io.File;
import javax.swing.JPanel;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 * This is the interface class for displaying the problem statement.
 * @author Maksud
 */
public class ProblemDisplay extends javax.swing.JFrame
{
    private UserDashboard dashboard;
    String problemID;

    /**
     * Creates new form ProblemDisplay
     */
    public ProblemDisplay(UserDashboard dashboard, String name, String time, String memory)
    {
        initComponents();
        this.dashboard = dashboard;
        ProblemNameLabel.setText(name);
        TimeLimitLabel.setText("Time Limit: "+time+" ms");
        MemoryLimitLabel.setText("Memory Limit: "+memory+" kb");
        this.setVisible(rootPaneCheckingEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        problemshow = new javax.swing.JPanel();
        ProblemNameLabel = new javax.swing.JLabel();
        TimeLimitLabel = new javax.swing.JLabel();
        MemoryLimitLabel = new javax.swing.JLabel();
        SubmitButton = new javax.swing.JButton();
        Separator = new javax.swing.JSeparator();
        pdfviewerpanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        problemshow.setBackground(new java.awt.Color(204, 255, 204));
        problemshow.setMaximumSize(new java.awt.Dimension(1920, 1440));
        problemshow.setMinimumSize(new java.awt.Dimension(1280, 720));

        ProblemNameLabel.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        ProblemNameLabel.setForeground(new java.awt.Color(102, 102, 255));
        ProblemNameLabel.setText("Problem Name");

        TimeLimitLabel.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        TimeLimitLabel.setForeground(new java.awt.Color(102, 102, 255));
        TimeLimitLabel.setText("Time Limit:");

        MemoryLimitLabel.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        MemoryLimitLabel.setForeground(new java.awt.Color(102, 102, 255));
        MemoryLimitLabel.setText("Memory Limit:");

        SubmitButton.setBackground(new java.awt.Color(153, 255, 255));
        SubmitButton.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        SubmitButton.setForeground(new java.awt.Color(51, 255, 51));
        SubmitButton.setText("Submit");
        SubmitButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        SubmitButton.setContentAreaFilled(false);
        SubmitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SubmitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SubmitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SubmitButtonButtonActionPerformed(evt);
            }
        });

        pdfviewerpanel.setMinimumSize(new java.awt.Dimension(1260, 560));
        pdfviewerpanel.setPreferredSize(new java.awt.Dimension(1260, 560));
        pdfviewerpanel.setLayout(new java.awt.BorderLayout());

        closeButton.setFont(new java.awt.Font("Product Sans", 1, 14)); // NOI18N
        closeButton.setText("Exit");
        closeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout problemshowLayout = new javax.swing.GroupLayout(problemshow);
        problemshow.setLayout(problemshowLayout);
        problemshowLayout.setHorizontalGroup(
            problemshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(problemshowLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(TimeLimitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MemoryLimitLabel)
                .addGap(100, 100, 100))
            .addGroup(problemshowLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pdfviewerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, problemshowLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Separator)
                .addGap(691, 691, 691))
            .addGroup(problemshowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProblemNameLabel)
                .addGap(403, 403, 403)
                .addComponent(closeButton)
                .addGap(155, 155, 155))
            .addGroup(problemshowLayout.createSequentialGroup()
                .addGap(584, 584, 584)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        problemshowLayout.setVerticalGroup(
            problemshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(problemshowLayout.createSequentialGroup()
                .addGroup(problemshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProblemNameLabel)
                    .addComponent(closeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(problemshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TimeLimitLabel)
                    .addComponent(MemoryLimitLabel))
                .addGap(11, 11, 11)
                .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pdfviewerpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        getContentPane().add(problemshow, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SubmitButtonButtonActionPerformed
    {//GEN-HEADEREND:event_SubmitButtonButtonActionPerformed
        dashboard.setTab(5, problemID);

        this.dispose();
    }//GEN-LAST:event_SubmitButtonButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
    {//GEN-HEADEREND:event_closeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MemoryLimitLabel;
    private javax.swing.JLabel ProblemNameLabel;
    private javax.swing.JSeparator Separator;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel TimeLimitLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel pdfviewerpanel;
    private javax.swing.JPanel problemshow;
    // End of variables declaration//GEN-END:variables
void viewPdf(File problem, String problemID)
    {
        this.problemID = problemID;
        SwingController controller = new SwingController(); 
        SwingViewBuilder factory = new SwingViewBuilder(controller);
        JPanel viwerpanel = factory.buildViewerPanel();
        pdfviewerpanel.add(viwerpanel);
        controller.openDocument(problem.getAbsolutePath());
    }
}

