/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iutforces_user;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * This is the interface class of the User Login GUI.
 * @author Rifat
 * @author Ishrak
 */
public class UserLogin extends javax.swing.JFrame
{
    /**
     * Creates new form UserLogin
     */
    private UserSocket userSocket;
    private UserSignup userSignup;
    private boolean isConnected;
    UserDashboard dashboard;
    public UserLogin(UserSocket userSocket)
    {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.setVisible(true);
        this.userSocket=userSocket;
        this.isConnected=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        RightPanel = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        CrNewAccButton = new javax.swing.JButton();
        leftSeparator = new javax.swing.JSeparator();
        orLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        PasswordLabel = new javax.swing.JLabel();
        StudentIDLabel = new javax.swing.JLabel();
        rightSeparator = new javax.swing.JSeparator();
        IPLabel = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        PortLabel = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        ConnectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        RightPanel.setBackground(new java.awt.Color(255, 153, 0));
        RightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeLabel.setFont(new java.awt.Font("Product Sans", 1, 36)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(51, 51, 51));
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeLabel.setText("User Login");
        RightPanel.add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 390, 70));

        closeLabel.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(51, 51, 51));
        closeLabel.setText("x");
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                closeLabelMouseClicked(evt);
            }
        });
        RightPanel.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 30, 20));

        minimizeLabel.setFont(new java.awt.Font("Arial", 1, 25)); // NOI18N
        minimizeLabel.setForeground(new java.awt.Color(51, 51, 51));
        minimizeLabel.setText("_");
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                minimizeLabelMouseClicked(evt);
            }
        });
        RightPanel.add(minimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, -10, 30, 40));

        txtStudentID.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        txtStudentID.setForeground(new java.awt.Color(102, 102, 102));
        txtStudentID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtStudentID.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                txtStudentIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                txtStudentIDFocusLost(evt);
            }
        });
        txtStudentID.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtStudentIDActionPerformed(evt);
            }
        });
        RightPanel.add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 270, 30));

        LoginButton.setBackground(new java.awt.Color(51, 51, 51));
        LoginButton.setFont(new java.awt.Font("Product Sans", 1, 20)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(51, 51, 51));
        LoginButton.setText("Login");
        LoginButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        LoginButton.setContentAreaFilled(false);
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoginButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LoginButtonActionPerformed(evt);
            }
        });
        RightPanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 80, 40));

        CrNewAccButton.setBackground(new java.awt.Color(51, 51, 51));
        CrNewAccButton.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        CrNewAccButton.setForeground(new java.awt.Color(51, 51, 51));
        CrNewAccButton.setText("New User? Create New Account");
        CrNewAccButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        CrNewAccButton.setContentAreaFilled(false);
        CrNewAccButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CrNewAccButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CrNewAccButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CrNewAccButtonButtonActionPerformed(evt);
            }
        });
        RightPanel.add(CrNewAccButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 310, 40));
        RightPanel.add(leftSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 180, 20));

        orLabel.setFont(new java.awt.Font("Product Sans", 0, 18)); // NOI18N
        orLabel.setForeground(new java.awt.Color(51, 51, 51));
        orLabel.setText("or");
        RightPanel.add(orLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 50, 20));

        PasswordField.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(102, 102, 102));
        PasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        PasswordField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PasswordFieldActionPerformed(evt);
            }
        });
        RightPanel.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 270, 30));

        PasswordLabel.setBackground(new java.awt.Color(51, 51, 51));
        PasswordLabel.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        PasswordLabel.setText("Password");
        RightPanel.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 120, 30));

        StudentIDLabel.setBackground(new java.awt.Color(51, 51, 51));
        StudentIDLabel.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        StudentIDLabel.setForeground(new java.awt.Color(51, 51, 51));
        StudentIDLabel.setText("Student ID");
        RightPanel.add(StudentIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 120, 30));
        RightPanel.add(rightSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 170, 40));

        IPLabel.setBackground(new java.awt.Color(51, 51, 51));
        IPLabel.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        IPLabel.setForeground(new java.awt.Color(51, 51, 51));
        IPLabel.setText("IP");
        RightPanel.add(IPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 30, 30));

        txtIP.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        txtIP.setForeground(new java.awt.Color(102, 102, 102));
        txtIP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtIP.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                txtIPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                txtIPFocusLost(evt);
            }
        });
        txtIP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtIPActionPerformed(evt);
            }
        });
        RightPanel.add(txtIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 240, 30));

        PortLabel.setBackground(new java.awt.Color(51, 51, 51));
        PortLabel.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        PortLabel.setForeground(new java.awt.Color(51, 51, 51));
        PortLabel.setText("Port");
        RightPanel.add(PortLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 50, 30));

        txtPort.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        txtPort.setForeground(new java.awt.Color(102, 102, 102));
        txtPort.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtPort.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                txtPortFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                txtPortFocusLost(evt);
            }
        });
        txtPort.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtPortActionPerformed(evt);
            }
        });
        RightPanel.add(txtPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 240, 30));

        ConnectButton.setBackground(new java.awt.Color(51, 51, 51));
        ConnectButton.setFont(new java.awt.Font("Product Sans", 1, 20)); // NOI18N
        ConnectButton.setForeground(new java.awt.Color(51, 51, 51));
        ConnectButton.setText("Connect");
        ConnectButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        ConnectButton.setContentAreaFilled(false);
        ConnectButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ConnectButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ConnectButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ConnectButtonButtonActionPerformed(evt);
            }
        });
        RightPanel.add(ConnectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_closeLabelMouseClicked
    {//GEN-HEADEREND:event_closeLabelMouseClicked
        try
        {
            userSocket.close();
        } 
        catch (IOException e)
        {
            Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, e);
        }
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_closeLabelMouseClicked

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_minimizeLabelMouseClicked
    {//GEN-HEADEREND:event_minimizeLabelMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);      // TODO add your handling code here:
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void txtStudentIDFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtStudentIDFocusGained
    {//GEN-HEADEREND:event_txtStudentIDFocusGained
        if(txtStudentID.getText().equals("Enter Student ID"))
        {
            txtStudentID.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIDFocusGained

    private void txtStudentIDFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtStudentIDFocusLost
    {//GEN-HEADEREND:event_txtStudentIDFocusLost
        if(txtStudentID.getText().equals(""))
        {
            txtStudentID.setText("Enter Student ID");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIDFocusLost

    private void txtStudentIDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtStudentIDActionPerformed
    {//GEN-HEADEREND:event_txtStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIDActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LoginButtonActionPerformed
    {//GEN-HEADEREND:event_LoginButtonActionPerformed
        if(!isConnected)
        {
            JOptionPane.showMessageDialog(null,"Connection Error!","Connection Status",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String studentID = txtStudentID.getText();
        String password = PasswordField.getText();
        String dataout = "Login---["+studentID+"]["+password+"]";
        System.out.println(dataout);
        if(userSocket.sendData(dataout)<0)
        {
            JOptionPane.showMessageDialog(null,"Timeout sending data!","Timeout",JOptionPane.ERROR_MESSAGE);
        }
        String datain = userSocket.readData();
        System.out.println(datain);             
        if(datain != null)
        {
            if(datain.equals("LoginTrue"))
            {
                JOptionPane.showMessageDialog(null,"Login Successful!","Status",JOptionPane.INFORMATION_MESSAGE);
                dashboard = new UserDashboard(userSocket,this);
                dashboard.setVisible(rootPaneCheckingEnabled);
                this.setVisible(false);
            }
            else if(datain.equals("LoginFalse"))
            {
                JOptionPane.showMessageDialog(null,"Incorrect Student ID Or Password!","Status",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Timeout reading data!","Timeout",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void CrNewAccButtonButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CrNewAccButtonButtonActionPerformed
    {//GEN-HEADEREND:event_CrNewAccButtonButtonActionPerformed
        if(!isConnected)
        {
            JOptionPane.showMessageDialog(null,"Connection Error!","Connection Status",JOptionPane.ERROR_MESSAGE);
            return;
        }
        userSignup = new UserSignup(userSocket);
        userSignup.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_CrNewAccButtonButtonActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PasswordFieldActionPerformed
    {//GEN-HEADEREND:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void txtIPFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtIPFocusGained
    {//GEN-HEADEREND:event_txtIPFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPFocusGained

    private void txtIPFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtIPFocusLost
    {//GEN-HEADEREND:event_txtIPFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPFocusLost

    private void txtIPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtIPActionPerformed
    {//GEN-HEADEREND:event_txtIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPActionPerformed

    private void txtPortFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtPortFocusGained
    {//GEN-HEADEREND:event_txtPortFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortFocusGained

    private void txtPortFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtPortFocusLost
    {//GEN-HEADEREND:event_txtPortFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortFocusLost

    private void txtPortActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtPortActionPerformed
    {//GEN-HEADEREND:event_txtPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortActionPerformed

    private void ConnectButtonButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConnectButtonButtonActionPerformed
    {//GEN-HEADEREND:event_ConnectButtonButtonActionPerformed
        int portNumber;
        try
        {
            portNumber= Integer.parseInt(txtPort.getText());
        }
        catch (NumberFormatException e)
        {
            portNumber = 0;
        }

        String ipAddress = txtIP.getText();
        if(userSocket.connect(ipAddress, portNumber) && portNumber!=0)
        {
            JOptionPane.showMessageDialog(null,"Connected!","Connection Status",JOptionPane.INFORMATION_MESSAGE);
            isConnected=true;
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Connection Error!","Connection Status",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ConnectButtonButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConnectButton;
    private javax.swing.JButton CrNewAccButton;
    private javax.swing.JLabel IPLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PortLabel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JLabel StudentIDLabel;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator leftSeparator;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JLabel orLabel;
    private javax.swing.JSeparator rightSeparator;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables
}
