/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package iutforces_admin;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 * This is the interface class for Admin Signup GUI.
 * @author Ishrak
 */
public class AdminSignup extends javax.swing.JFrame 
{
    AdminSocket adminSocket;

    /** Creates new form AdminSignup */
    public AdminSignup(AdminSocket adminSocket) 
    {
        initComponents();
        txtUsername.setFocusable(true);
        this.adminSocket=adminSocket;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        RightPanel = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        SignUpButton = new javax.swing.JButton();
        AlreadyAccButton = new javax.swing.JButton();
        leftSeparator = new javax.swing.JSeparator();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        RightPanel.setBackground(new java.awt.Color(204, 102, 255));
        RightPanel.setForeground(new java.awt.Color(51, 51, 51));
        RightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeLabel.setFont(new java.awt.Font("Product Sans", 1, 36)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(51, 51, 51));
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeLabel.setText("Admin Signup");
        RightPanel.add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 400, 70));

        closeLabel.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(51, 51, 51));
        closeLabel.setText("x");
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                closeLabelMouseClicked(evt);
            }
        });
        RightPanel.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 30, 20));

        minimizeLabel.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        minimizeLabel.setForeground(new java.awt.Color(51, 51, 51));
        minimizeLabel.setText("_");
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                minimizeLabelMouseClicked(evt);
            }
        });
        RightPanel.add(minimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -10, 30, 40));

        txtUsername.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(102, 102, 102));
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                txtUsernameFocusLost(evt);
            }
        });
        RightPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 270, 30));

        SignUpButton.setBackground(new java.awt.Color(0, 181, 204));
        SignUpButton.setFont(new java.awt.Font("Product Sans", 1, 20)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(51, 51, 51));
        SignUpButton.setText("Sign Up");
        SignUpButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        SignUpButton.setContentAreaFilled(false);
        SignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SignUpButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SignUpButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SignUpButtonActionPerformed(evt);
            }
        });
        RightPanel.add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 90, 40));

        AlreadyAccButton.setBackground(new java.awt.Color(0, 181, 204));
        AlreadyAccButton.setFont(new java.awt.Font("Product Sans", 1, 20)); // NOI18N
        AlreadyAccButton.setForeground(new java.awt.Color(51, 51, 51));
        AlreadyAccButton.setText("Already have an account? Login!");
        AlreadyAccButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        AlreadyAccButton.setContentAreaFilled(false);
        AlreadyAccButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AlreadyAccButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AlreadyAccButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AlreadyAccButtonButtonActionPerformed(evt);
            }
        });
        RightPanel.add(AlreadyAccButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 360, 40));
        RightPanel.add(leftSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 390, 20));

        ConfirmPasswordField.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        ConfirmPasswordField.setForeground(new java.awt.Color(102, 102, 102));
        ConfirmPasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        RightPanel.add(ConfirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 270, 30));

        ConfirmPasswordLabel.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        ConfirmPasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        ConfirmPasswordLabel.setText("Confirm Password");
        RightPanel.add(ConfirmPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 180, 30));

        UsernameLabel.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(51, 51, 51));
        UsernameLabel.setText("Username");
        RightPanel.add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 120, 30));

        PasswordLabel.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        PasswordLabel.setText("Password");
        RightPanel.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 120, 30));

        PasswordField.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(102, 102, 102));
        PasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        RightPanel.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 237, 270, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 610, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 152, Short.MAX_VALUE)
                    .addComponent(RightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_closeLabelMouseClicked
    {//GEN-HEADEREND:event_closeLabelMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_closeLabelMouseClicked

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_minimizeLabelMouseClicked
    {//GEN-HEADEREND:event_minimizeLabelMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);      // TODO add your handling code here:
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtUsernameFocusGained
    {//GEN-HEADEREND:event_txtUsernameFocusGained
        if(txtUsername.getText().equals("Enter Username"))
        {
            txtUsername.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtUsernameFocusLost
    {//GEN-HEADEREND:event_txtUsernameFocusLost
        if(txtUsername.getText().equals(""))
        {
            txtUsername.setText("Enter Username");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameFocusLost

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SignUpButtonActionPerformed
    {//GEN-HEADEREND:event_SignUpButtonActionPerformed
        String username = txtUsername.getText();
        String password = PasswordField.getText();
        String confirmPassword = ConfirmPasswordField.getText();
        if(password.equals(confirmPassword)==false)
        {
            ConfirmPasswordField.setText("");
            JOptionPane.showMessageDialog(null, "Password didn't match", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if(adminSocket.sendData("SignUp--["+username+"]["+password+"]")<0)
            {
                JOptionPane.showMessageDialog(null, "Socket write error", "Connection!!!", JOptionPane.ERROR_MESSAGE);
            }

            String temp = adminSocket.readData();
            System.out.println("Temp: "+temp);

            if(temp.equals("Exist---"))
            {
                JOptionPane.showMessageDialog(null, "Username already exist", "SignUP", JOptionPane.INFORMATION_MESSAGE);
            }
            else if(temp.equals("SignUpTr"))
            {
                JOptionPane.showMessageDialog(null, "SignUp Successful", "SignUP", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "SignUp Failed", "SignUp!!!", JOptionPane.ERROR_MESSAGE);
            }
        }      // TODO add your handling code here:
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void AlreadyAccButtonButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AlreadyAccButtonButtonActionPerformed
    {//GEN-HEADEREND:event_AlreadyAccButtonButtonActionPerformed
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_AlreadyAccButtonButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlreadyAccButton;
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator leftSeparator;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
