/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iutforces_admin;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * This is the interface class of the Admin Login GUI.
 * @author Ishrak
 */
public class AdminLogin extends javax.swing.JFrame
{

    /**
     * Creates new form AdminLogin
     */
    private AdminSocket adminSocket;
    private AdminSignup adminSignup;
    AdminDashboard dashboard;
    private boolean isConnected;
    public AdminLogin(AdminSocket adminSocket)
    {
        initComponents();
        this.setVisible(true);
        this.adminSocket=adminSocket;
        this.isConnected=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        RightPanel = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        PasswordLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        leftSeparator = new javax.swing.JSeparator();
        orLabel = new javax.swing.JLabel();
        rightSeparator = new javax.swing.JSeparator();
        CreateNewAccountButton = new javax.swing.JButton();
        IPLabel = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        PortLabel = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        ConnectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        RightPanel.setBackground(new java.awt.Color(153, 255, 153));
        RightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeLabel.setFont(new java.awt.Font("Product Sans", 1, 38)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(51, 51, 51));
        WelcomeLabel.setText("Admin Panel");
        RightPanel.add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 240, 70));

        closeLabel.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(204, 153, 255));
        closeLabel.setText("x");
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                closeLabelMouseClicked(evt);
            }
        });
        RightPanel.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 30, 20));

        minimizeLabel.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        minimizeLabel.setForeground(new java.awt.Color(204, 153, 255));
        minimizeLabel.setText("_");
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                minimizeLabelMouseClicked(evt);
            }
        });
        RightPanel.add(minimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 30, -1));

        txtUsername.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(102, 102, 102));
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                txtUsernameFocusLost(evt);
            }
        });
        RightPanel.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 270, 30));

        LoginButton.setBackground(new java.awt.Color(0, 0, 0));
        LoginButton.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(51, 51, 51));
        LoginButton.setText("Login");
        LoginButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        LoginButton.setContentAreaFilled(false);
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoginButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LoginButtonActionPerformed(evt);
            }
        });
        RightPanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 80, 40));

        PasswordField.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(102, 102, 102));
        PasswordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        RightPanel.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 270, 30));

        PasswordLabel.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(51, 51, 51));
        PasswordLabel.setText("Password");
        RightPanel.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 120, 30));

        UsernameLabel.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(51, 51, 51));
        UsernameLabel.setText("Username");
        RightPanel.add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 120, 30));
        RightPanel.add(leftSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 180, 20));

        orLabel.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        orLabel.setForeground(new java.awt.Color(102, 102, 102));
        orLabel.setText("or");
        RightPanel.add(orLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 50, 20));
        RightPanel.add(rightSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 170, 40));

        CreateNewAccountButton.setBackground(new java.awt.Color(204, 102, 255));
        CreateNewAccountButton.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        CreateNewAccountButton.setForeground(new java.awt.Color(51, 51, 51));
        CreateNewAccountButton.setText("New Admin? Create New Account");
        CreateNewAccountButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        CreateNewAccountButton.setContentAreaFilled(false);
        CreateNewAccountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CreateNewAccountButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CreateNewAccountButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CreateNewAccountButtonButtonActionPerformed(evt);
            }
        });
        RightPanel.add(CreateNewAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 340, 40));

        IPLabel.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        IPLabel.setForeground(new java.awt.Color(51, 51, 51));
        IPLabel.setText("IP");
        RightPanel.add(IPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 30, 30));

        txtIP.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        txtIP.setForeground(new java.awt.Color(102, 102, 102));
        txtIP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtIP.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                txtIPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                txtIPFocusLost(evt);
            }
        });
        txtIP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtIPActionPerformed(evt);
            }
        });
        RightPanel.add(txtIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, 30));

        PortLabel.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        PortLabel.setForeground(new java.awt.Color(51, 51, 51));
        PortLabel.setText("Port");
        RightPanel.add(PortLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 50, 30));

        txtPort.setFont(new java.awt.Font("Product Sans", 0, 20)); // NOI18N
        txtPort.setForeground(new java.awt.Color(102, 102, 102));
        txtPort.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 102, 102)));
        txtPort.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                txtPortFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                txtPortFocusLost(evt);
            }
        });
        txtPort.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtPortActionPerformed(evt);
            }
        });
        RightPanel.add(txtPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 250, 30));

        ConnectButton.setBackground(new java.awt.Color(204, 102, 255));
        ConnectButton.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        ConnectButton.setForeground(new java.awt.Color(51, 51, 51));
        ConnectButton.setText("Connect");
        ConnectButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 181, 204)));
        ConnectButton.setContentAreaFilled(false);
        ConnectButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ConnectButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ConnectButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ConnectButtonButtonActionPerformed(evt);
            }
        });
        RightPanel.add(ConnectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 689, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 145, Short.MAX_VALUE)
                    .addComponent(RightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(RightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_closeLabelMouseClicked
    {//GEN-HEADEREND:event_closeLabelMouseClicked
        try
        {
            adminSocket.close();
        }
        catch(IOException ex)
        {
            Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_closeLabelMouseClicked

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_minimizeLabelMouseClicked
    {//GEN-HEADEREND:event_minimizeLabelMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);      // TODO add your handling code here:
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtUsernameFocusGained
    {//GEN-HEADEREND:event_txtUsernameFocusGained
        if(txtUsername.getText().equals("Enter Username"))
        {
            txtUsername.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtUsernameFocusLost
    {//GEN-HEADEREND:event_txtUsernameFocusLost
        if(txtUsername.getText().equals(""))
        {
            txtUsername.setText("Enter Username");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameFocusLost

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LoginButtonActionPerformed
    {//GEN-HEADEREND:event_LoginButtonActionPerformed

        if(!isConnected)
        {
            JOptionPane.showMessageDialog(null,"Connection Error!","Connection Status",JOptionPane.ERROR_MESSAGE);
            return;
        }

        String username = txtUsername.getText();
        String password = PasswordField.getText();
        String dataout = "Login---["+username+"]["+password+"]";
        System.out.println(dataout);
        if(adminSocket.sendData(dataout)<0)
        {
            JOptionPane.showMessageDialog(null,"Timeout sending data!","Timeout",JOptionPane.ERROR_MESSAGE);
        }

        String datain=adminSocket.readData();
        System.out.println("data read");
        System.out.println("datain: "+datain);
        if(datain != null)
        {
            if(datain.equals("LoginTrue"))
            {
                JOptionPane.showMessageDialog(null,"Login Successful!","Status",JOptionPane.INFORMATION_MESSAGE);
                dashboard = new AdminDashboard(adminSocket,this);
                this.setVisible(false);
            }
            else if(datain.equals("LoginFailure"))
            {
                JOptionPane.showMessageDialog(null,"Incorrect Username Or Password!","Status",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Timeout reading data!","Timeout",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void CreateNewAccountButtonButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CreateNewAccountButtonButtonActionPerformed
    {//GEN-HEADEREND:event_CreateNewAccountButtonButtonActionPerformed
        if(!isConnected)
        {
            JOptionPane.showMessageDialog(null,"Connection Error!","Connection Status",JOptionPane.ERROR_MESSAGE);
            return;
        }
        adminSignup = new AdminSignup(adminSocket);
        adminSignup.setVisible(rootPaneCheckingEnabled);

    }//GEN-LAST:event_CreateNewAccountButtonButtonActionPerformed

    private void txtIPFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtIPFocusGained
    {//GEN-HEADEREND:event_txtIPFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPFocusGained

    private void txtIPFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtIPFocusLost
    {//GEN-HEADEREND:event_txtIPFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPFocusLost

    private void txtIPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtIPActionPerformed
    {//GEN-HEADEREND:event_txtIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPActionPerformed

    private void txtPortFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtPortFocusGained
    {//GEN-HEADEREND:event_txtPortFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortFocusGained

    private void txtPortFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_txtPortFocusLost
    {//GEN-HEADEREND:event_txtPortFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortFocusLost

    private void txtPortActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtPortActionPerformed
    {//GEN-HEADEREND:event_txtPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortActionPerformed

    private void ConnectButtonButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConnectButtonButtonActionPerformed
    {//GEN-HEADEREND:event_ConnectButtonButtonActionPerformed
        int portNumber;
        try
        {
            portNumber= Integer.parseInt(txtPort.getText());
        }
        catch (NumberFormatException e)
        {
            portNumber = 0;
        }
        String ip=txtIP.getText();
        if(adminSocket.connect(ip, portNumber) && portNumber!=0)
        {
            JOptionPane.showMessageDialog(null,"Connected!","Connection Status",JOptionPane.INFORMATION_MESSAGE);
            isConnected=true;
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Connection Error!","Connection Status",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ConnectButtonButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConnectButton;
    private javax.swing.JButton CreateNewAccountButton;
    private javax.swing.JLabel IPLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PortLabel;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator leftSeparator;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JLabel orLabel;
    private javax.swing.JSeparator rightSeparator;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
